version: '3.7'
services:
  api:
    build: .
    command: python -u app.py "mongodb"
    ports:
      - 5000:5000
    volumes:
      - .:/todo 
    links:
      - db

  db:
    image: mongo:latest
    hostname: mongodb
    ports:
      - 27017:27017
